### ISSUE TITLE
[REFACTORING] Remove dead code

### ISSUE THREAD

**Issue by gregorybesson** [abecms/abecms#1]
https://github.com/AdFabConnect/abejs/blob/7495105387309365c4e10ab59be2b475f6d87b62/src/cli/helpers/abe-sql.js#L433

Remove any reference to "template" in the code. This attribute was a "magic keyword" and should be replaced by its real "name" : abe_meta.template.

**Comment by nicolaslabbe** [comment]
Add documentation https://github.com/AdFabConnect/abejs/blob/master/docs/abe-sql.md
