### ISSUE TITLE
Unable to select template in AbeJS Admin

### ISSUE THREAD

**Issue by diskosteven** [abecms/abecms#10]
I wasn't able to select my template in AbeJS admin because my NodeJS version was 4.6.0

I've just upgraded to the last version with the following command on OSX (certainly the same for Linux) :
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

Works well now

**Comment by gregorybesson** [comment]
Hello Steven,

TY for the comment. I let the bug open as we have to make Abe compliant with the Node 4.x version !

**Comment by gregorybesson** [comment]
fixed by commit e013378e2a4f718826acbdbe4c56b5572563beeb
