### ISSUE TITLE
Bug syntaxe {{variable}} dans l'attribut FILE du tag ABE IMPORT

### ISSUE THREAD

**Issue by e-ilyasse** [abecms/abecms#103]
Hello,

Lorsque qu'on utilise le tag import avec des variable dynamique pour le nom du fichier à importer la syntaxe à utiliser pour les {{variables}} n'est pas la même que dans handlebars.

Par exemple voici un import d'un fichier qui se fait en fonction de la langue dans les pré-contrib:
{{abe type='import' file='header_{{language[0].value}}.html'}}

Voici la syntaxe Handlebars à utiliser pour récupérer la même valeur:
{{language.[0].value}}    (Il faut mettre un point avant le [0])

Idéalement il faudra que la syntaxe des variables dynamiques utiliser pour faire les tags ABE imports soit la même que handlebars.

**Comment by gregorybesson** [comment]
fixed in 2.15.0 to come.

It will now be possible to use:
- {{language[0].value}}
- {{language.[0].value}}
- {{language.0..value}}

which will produce the same result.
