### ISSUE TITLE
Create user management system in back-office

### ISSUE THREAD

**Issue by bpcampeau** [abecms/abecms#115]
Currently, to enable/disable the login logic, the user is required to change the abe.json file and remove the setting by hand.

The best use case would be to be able to create users and user groups from the back office.

A few things that should be added:

- On abe first access, we should be forced to initiate an admin user
- There should be a checkmark in the user management to enable dev mode which removes the encumbrance of login each time when headers resets.
- (The dev check mark) should prompt a pop up warning the user that this should be only used in dev environment and exposes the user to possible problems (Or simply PREVENT the option from appearing if abe is launched in production)
- Put a picture upload for a profile (Not mendatory)
- Each user should be bound to an email address for quick recuperation of password

**Comment by gregorybesson** [comment]
80% of your request is already included in the current version. I'll do a specific recipe to demo the features.

Stay tuned !

**Comment by gregorybesson** [comment]
3.0.0
