### ISSUE TITLE
Create a mobile preview viewer

### ISSUE THREAD

**Issue by bpcampeau** [abecms/abecms#116]
Since Abe uses iframes, it's impossible to see the preview of the page in emulation mode like Chrome, IE and Firefox.

I suggest creating a Mobile viewer with popular viewports tablet, mobile, desktop. Could be layered with icons so it's easy to manage. 

When the viewport is selected, there should be a custom size picker for more precise testing depending of the view port.

**Comment by gregorybesson** [comment]
3.0.0

The custom size picker will not be available in this version
