### ISSUE TITLE
Status DRAFT displayed in the manager 

### ISSUE THREAD

**Issue by opompilius** [abecms/abecms#13]
- Add tooltip on the label (date of the content)

**Comment by gregorybesson** [comment]
@opompilius This topic should be discussed: I think it's time to review the manager to improve its usability and UX.

**Comment by nicolaslabbe** [comment]
Fix bug on manager status publish date

**Comment by gregorybesson** [comment]
UX on the manager will be part of a specific release dev in the 2.x series
