### ISSUE TITLE
Upgrade from 2.13.* to 2.16.4

### ISSUE THREAD

**Issue by GG31** [abecms/abecms#150]
For the each in the json files. If no data is in the each array article, the json generated is :
"article": [
    ""
  ]
In the BO, the consequences are :
 - at least one item is created by default with empty fields, removing it as no effect
 - if there is a link field, it is filled with : "function link() { [native code] }"
 - if we have a condition on the array length in the template, we cannot check if the array is really empty or not unless checking all fields content inside the first item

If we remove the "" in the json file, as there is only article in the tab, the entire tab is not displayed
There is no problem if the array has more than one item.

The issue is reproduced with the 2.15 but not with 2.14.7

**Comment by gregorybesson** [comment]
Fixed in the next version to come
