### ISSUE TITLE
Abe serve does not push an updated asset file if its size remains the same

### ISSUE THREAD

**Issue by cedouard** [abecms/abecms#156]
It appears that modifying an asset file, for instance when you change only 1 character, is problematic (ie. replacing "_320px;_" by "_380px;_"). The updated file is never pushed in the "_site_" folder on a **Abe serve** command. 

To bypass this problematic, I had to add an empty comment in toder to change the file size. Then - only - , Abe pushed the updated file.

**Comment by wonknu** [comment]
PR is pending https://github.com/abecms/abecms/pull/158
