### ISSUE TITLE
Data json file too large because of select request

### ISSUE THREAD

**Issue by opompilius** [abecms/abecms#192]
In a request like "select thematic,title,meta_description,filename_of_the_main_image from ../ where template !='hub'" max-length="4" min-length='4'", it seems that all content requested are kept in the json data file, and not only the 4 content expected.

**Comment by gregorybesson** [comment]
It has been fixed in v3.0.0 but a refactoring has to be done. data in select shouldn't be part of a json document unless they have been selected by the doc.
