### ISSUE TITLE
windows image upload bug

### ISSUE THREAD

**Issue by Hyowon22** [abecms/abecms#215]
When uploading an image in the backend, the double backslash appears in the input box 
i.e. \\\image\too-cute-doggone-it-video-playlist-1-29e8.jpg\

image.js `resp['filePath'] = path.posix.join('/' + folderWebPath, slug)`

If we manually remove the backslash, it temporarily resolves it

**Comment by gregorybesson** [comment]
This bug seems related to Windows. 

To fix this, we should have the URL and not the PATH in the input box. 

Fix planned in the next version: 3.2.2 and 2.16.*
Timeframe : 1d

**Comment by wonknu** [comment]
Pending PR: https://github.com/abecms/abecms/pull/216

**Comment by gregorybesson** [comment]
fixed in both versions
