### ISSUE TITLE
Recursive object in a {{#each}} are saved correctly but don't display

### ISSUE THREAD

**Issue by gregorybesson** [abecms/abecms#235]
example:
<ul>
{{#each record}}
<li>
    {{abe type='text' key='record.title' desc='Talk title'}}
    {{abe type='text' key='record.client.name' desc='client'}}
</li>
{{/each}}
</ul>

This snippet displays correctly the fields in the editor + save the json correctly but the client.name  value doesn't appear anymore in the form after save

**Comment by NRAUBER** [comment]
:-)

**Comment by nicolaslabbe** [comment]
PR: https://github.com/abecms/abecms/pull/237

**Comment by gregorybesson** [comment]
fixed in v3.5.0
