### ISSUE TITLE
Error in doc abe-translate.md

### ISSUE THREAD

**Issue by NRAUBER** [abecms/abecms#236]
Their is an error here : abecms/docs/types/abe-translate.md

http://files.joyjet.com/niko/screens/nrauber_abecmsabe-translate.md_at_b18dd4b9b321740064ea3ea69e6ad487844912a3__abecmsabecms_2017-09-27_18-32-44.png

bise

**Comment by gregorybesson** [comment]
Thx @NRAUBER fixed !
