### ISSUE TITLE
Feature : Global variables 

### ISSUE THREAD

**Issue by NRAUBER** [abecms/abecms#262]
Create a Abe attribute that will allow a variable to be shared bettween multiple templates.
Good exemple can be a logo img src that will be editable and shared across all the site.

**Comment by gregorybesson** [comment]
Since version 3.5.x, an abe tag can be provided with a `source` attribute which gives the ability to reuse the same "variable" across multiples templates.

{{abe type="text" desc="copyright" key=copyright source="/reference/copyright"}}
