### ISSUE TITLE
How can I redirect the  base url / to another page like /fr/index.html by passing the authentication

### ISSUE THREAD

**Issue by wilofice** [abecms/abecms#278]
Hello, 

Thanks for the great work you've done with the abecms. Please how can I make localhost:3000/ redirect to my website directly like localhost:3000/fr/index.html? I tried .htaccess and trying modifing your code but it does not work. 
Thanks

**Comment by wilofice** [comment]
Please,  help me thanks

**Comment by gregorybesson** [comment]
Hello @wilofice sorry for the delay : You should already be able to have this kind of url.

If you want to create multilingual websites (like localhost:3000/fr localhost:3000/en ...) you just have to create 2 subdirectories in the directory /structure like so:

/structure/fr
/structure/en

Then, when you'll create an index page from your template in Abe, just select the subdirectory you want (fr or en). That's all !

**Comment by wilofice** [comment]
Thanks for your reply :). It was helpful
