### ISSUE TITLE
abecms / Node 15.10.0

### ISSUE THREAD

**Issue by nashvinxtn** [abecms/abecms#284]
Created a projet with abecms (version 3.2.3). i installed it with node 10.22
I have updated my node to latest version 15.10.0 but can't make the projet to work again locally. Getting errors after errors & its building after abeserve but page not showing.

MSG :
website started : G:\xampp73\htdocs\abe-cms\abe
(node:19380) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
You are in development mode
which means every change in your themes (templates, partials and assets), reference and structure folders will dynamically update your site
In production, this mode shouldn't be used.
the directory G:\xampp73\htdocs\abe-cms\abe\structure does not exist
the directory G:\xampp73\htdocs\abe-cms\abe\locales does not exist
(node:1312) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Livereload listening on 35729

server running at http://localhost:3000/
Manager updated

**Comment by gregorybesson** [comment]
There was no error in your trace : https://www.mongodb.com/community/forums/t/warning-accessing-non-existent-property-mongoerror-of-module-exports-inside-circular-dependency/15411

Without more clues, I must close this one.
