### ISSUE TITLE
WYSIWYG editor (rich) - Line break

### ISSUE THREAD

**Issue by julienlegac** [abecms/abecms#35]
If use line break, the second paragraph create a independant <div> outside global paragraph.
Styles are not applied.

**Comment by gregorybesson** [comment]
Hello @diskojulienlg : By linebreak, you mean <br/> ?

**Comment by gregorybesson** [comment]
The linebreak close the style which was applied previously

**Comment by gregorybesson** [comment]
The wysiwyg works this way:
- If you hit "return", it will create a new paragraph
-If you hit "Shift"+"return", you will obtain a linebreak (<br/>) in the same paragraph
