### ISSUE TITLE
Add the attribute "toolbar" to rich abe type

### ISSUE THREAD

**Issue by opompilius** [abecms/abecms#53]
This attribute allows to configure the RTE toolbar displaying more or less actions

**Comment by gregorybesson** [comment]
The attribute should be named : "toolbar"

the options possible (no middle nor low keywords as they don't mean anything):
{{abe type="rich" desc="wysiwyg" key="myInput" toolbar="full"}}
{{abe type="rich" desc="wysiwyg" key="myInput" toolbar="bold,italic,underline,text-color,bg-color,align,subscript,superscript,indent,list,link,code"}}

full means all options
align includes align-left, align-right, align-center and align-justify
indent includes indent and outdent
