### ISSUE TITLE
Abe type "rich" : Possibility to add a reference file in the toolbar

### ISSUE THREAD

**Issue by opompilius** [abecms/abecms#55]
When the attribute "toolbar" refers to a json data source file (references), a dropdown list with keys is displayed on the editor. if a key is selected, the value is used in the wysiwyg enclosed in an Abe tag with the key. So that the key is displayed and the value is shown on mouse over.
In the template, we do the same : If we're in the editor mode, the key is displayed and highlighted with a specific color. On mouse over, we show the value.
In preview and publish mode, we remove the abe type and just let the value.

**Comment by gregorybesson** [comment]
A reference file is a key->value file.

**Comment by gregorybesson** [comment]
We won't implement this feature this way.
