### ISSUE TITLE
Refactor: abe_meta date

### ISSUE THREAD

**Issue by nicolaslabbe** [abecms/abecms#70]
Json post `abe_meta...date` need a refactor.
At this time when a post is created

```javascript
{
  "abe_meta": {
    "date": new Date(),
    "draft": {
      "date": new Date(),
      "latest": {
        "date": new Date()
      }
    }
}
```

After a [ status ] is saved

```javascript
{
  "abe_meta": {
    "date": stay the same,
    "latest": {
        "date": new Date()
      },
    "[ status ]": {
      "date": stay the same if exist,
      "latest": {
        "date": new Date()
      }
    }
}
```

each new draft `abe_meta.[ status ].latest.date` and  `abe_meta.latest.date` is update with a new date.

**Comment by nicolaslabbe** [comment]
delete `abe_meta.date`
add `abe_meta.createdDate`
add `abe_meta.modifiedDate`
add `abe_meta.createdAuthor`
add `abe_meta.modifiedAuthor`
`abe_meta.status` is now a string with status

**Comment by gregorybesson** [comment]
3.1.0
