### ISSUE TITLE
Selected value lost after saving

### ISSUE THREAD

**Issue by Roatha-Chann** [abecms/abecms#79]
I have this kind of select input for languages: {{abe type='data' key='language' desc='Language' source='reference/language.json' display="display" required="true" tab="slug" visible="false" max-length="1"}}

And I want to use it as follows: {{abe type="translate" source="points" locale="{{language.[0].value}}"}}

When I first create a page and select whatever language, it displays the right translations, but if I click save, it goes back to the first/language of my language.json.

**Comment by nicolaslabbe** [comment]
Already fixed on abe@2.12.0
