### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by nicolaslabbe** [abecms/abecms#85]
A group is dynamically created when we put a prefix in a key of an abe tag:
{{abe type="text" key="mygroup.title" desc="title}}
{{abe type="text" key="mygroup.description" desc="description}}

It's now possible to add a group description with "groupdesc".

What needs to be changed:
groupdesc must become "group".

- If a prefix in the key exist, it must be presented as a group.
- if there is no prefix but the 'group' attribute exists, we must represent the inputs with the same 'group' as a group.

**Comment by gregorybesson** [comment]
fixed in 3.0.0
