### ISSUE TITLE
highlight of editing text not working in dynamic partials

### ISSUE THREAD

**Issue by Roatha-Chann** [abecms/abecms#89]
highlight of currently edited text not working in dynamically imported partials.
Using this code for example:

{abe type='text' key='lcah_main_block_cta' desc='Main block cta' tab='Main block' visible="false"}}

{{abe type='import' file='LCAH_main_block_{{lcah_main_block_style[0].value}}.html'}}

if element 'lcah_main_block_cta' is visible in partial.

**Comment by nicolaslabbe** [comment]
Working on abe@2.12.0

Maybe you missed the double `{` ?
`{abe type='text' key='lcah_main_block_cta'` should be `{{abe type='text' key='lcah_main_block_cta'`
