### ISSUE TITLE
Select input not working anymore

### ISSUE THREAD

**Issue by Roatha-Chann** [abecms/abecms#90]
{{abe type='data' key='colors' desc='Pick a color' source='["red", "green", "yellow"]'}}
does not show a typical select input anymore but some kind of selectable options in a list.

**Comment by gregorybesson** [comment]
Hello @Roatha-Chann : This is the expected behavior.
If you don't limit de number of selectable items, we'll display a list in which you can make multiple selections.

If you want to obtain a dropdownlist, limit de number of expected elements to one:

```
{{abe type='data' key='colors' desc='Pick a color' source='["red", "green", "yellow"]' max-length='1'}}
```

Ok for you ?
